table Accounts

	column 'Account Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Account Name

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

	column 'State or Province'
		dataType: string
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: State or Province

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

	column Country
		dataType: string
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

	column AccountID
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: AccountID

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation PBI_ChangedProperties = ["IsHidden"]

	column AccountSeq
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: AccountSeq

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation PBI_ChangedProperties = ["IsHidden"]

	column IndustrySeq
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: IndustrySeq

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation PBI_ChangedProperties = ["IsHidden"]

	column AccountOwnerSeq
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: sum
		sourceColumn: AccountOwnerSeq

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation PBI_ChangedProperties = ["IsHidden"]

	column 'Account Number'
		dataType: string
		summarizeBy: none
		sourceColumn: Account Number

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

	column TerritorySeq
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: TerritorySeq

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation PBI_ChangedProperties = ["IsHidden"]

	hierarchy 'Street Hierarchy'

		level 'Account Name'
			column: 'Account Name'

		level 'State or Province'
			column: 'State or Province'

		level Country
			column: Country

	partition Accounts-569e2118-8ef4-4f17-9647-c9b4190bc0c8 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://microsoft-my.sharepoint.com/personal/misewell_microsoft_com/Documents/Documents/GitHub/ContosoBI/Contoso%20-%20Sales%20-%20Current%20Release/Contoso%20-%20Dynamics%20365%20Sales%20Source%20Data.xlsx"), null, true),
				    AccountTbl_Table = Source{[Item="AccountTbl",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(AccountTbl_Table,{{"AccountSeq", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Distribution%", "DistributionAccumulation", "City"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Columns", each [AccountSeq] <> null and [AccountSeq] <> ""),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Filtered Rows",{{"AccountSeq", Int64.Type}, {"AccountID", type text}, {"Account Number", type text}, {"Account Name", type text},{"State or Province", type text}, {"Country", type text}, {"TerritorySeq", Int64.Type}, {"AccountOwnerSeq", Int64.Type}, {"IndustrySeq", Int64.Type}})
				in
				    #"Changed Type1"

	annotation PBI_QueryRelationships = {"columnCount":19,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Section1/Accounts/Changed Type.{AccountSeq,0}","Section1/Accounts/Changed Type.{Account Name,1}","Section1/Accounts/Changed Type.{AccountID,2}","Section1/Accounts/Changed Type.{Street,3}","Section1/Accounts/Changed Type.{City,4}","Section1/Accounts/Changed Type.{State or Province,5}","Section1/Accounts/Changed Type.{Postal Code,6}","Section1/Accounts/Changed Type.{Country,7}","Section1/Accounts/Changed Type.{Latitude,8}","Section1/Accounts/Changed Type.{Longitude,9}","Section1/Accounts/Changed Type.{Phone,10}","Section1/Accounts/Changed Type.{Number of Employees,11}","Section1/Accounts/Changed Type.{Annual Revenue,12}","Section1/Accounts/Changed Type.{AccountOwnerSeq,13}","Section1/Accounts/Changed Type.{IndustrySeq,14}","Section1/Accounts/Changed Type.{Account Owner,15}","Section1/Accounts/Changed Type.{Industry,16}","Section1/Accounts/Changed Type.{Territory,17}","Section1/Accounts/Changed Type.{Region,18}"],"ColumnCount":19,"KeyColumnNames":[],"ColumnIdentities":["Section1/Accounts/Changed Type.{AccountSeq,0}","Section1/Accounts/Changed Type.{Account Name,1}","Section1/Accounts/Changed Type.{AccountID,2}","Section1/Accounts/Changed Type.{Street,3}","Section1/Accounts/Changed Type.{City,4}","Section1/Accounts/Changed Type.{State or Province,5}","Section1/Accounts/Changed Type.{Postal Code,6}","Section1/Accounts/Changed Type.{Country,7}","Section1/Accounts/Changed Type.{Latitude,8}","Section1/Accounts/Changed Type.{Longitude,9}","Section1/Accounts/Changed Type.{Phone,10}","Section1/Accounts/Changed Type.{Number of Employees,11}","Section1/Accounts/Changed Type.{Annual Revenue,12}","Section1/Accounts/Changed Type.{AccountOwnerSeq,13}","Section1/Accounts/Changed Type.{IndustrySeq,14}","Section1/Accounts/Changed Type.{Account Owner,15}","Section1/Accounts/Changed Type.{Industry,16}","Section1/Accounts/Changed Type.{Territory,17}","Section1/Accounts/Changed Type.{Region,18}"],"RelationshipInfo":[]}

	annotation PBI_ResultType = Table

