table Campaigns

	column CampaignSeq
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: CampaignSeq

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation PBI_ChangedProperties = ["IsHidden"]

	column 'Campaign Type'
		dataType: string
		summarizeBy: none
		sourceColumn: Campaign Type

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

	column Campaign
		dataType: string
		summarizeBy: none
		sourceColumn: Campaign

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

	partition Campaigns-3cb88e48-13a8-4187-b349-6b06275a3f32 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://microsoft-my.sharepoint.com/personal/misewell_microsoft_com/Documents/Documents/GitHub/ContosoBI/Contoso%20-%20Sales%20-%20Current%20Release/Contoso%20-%20Dynamics%20365%20Sales%20Source%20Data.xlsx"), null, true),
				    CampaignsTbl_Table = Source{[Item="CampaignsTbl",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(CampaignsTbl_Table,{{"CampaignSeq", Int64.Type}, {"Type", type text}, {"Name", type text}, {"Factor", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Factor", "Distribution%", "DistributionAccumulation"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Type", "Campaign Type"}, {"Name", "Campaign"}})
				in
				    #"Renamed Columns"

	annotation PBI_QueryRelationships = {"columnCount":4,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Section1/Campaigns/Changed Type.{CampaignSeq,0}","Section1/Campaigns/Changed Type.{Type,1}","Section1/Campaigns/Changed Type.{Name,2}","Section1/Campaigns/Changed Type.{Factor,3}"],"ColumnCount":4,"KeyColumnNames":[],"ColumnIdentities":["Section1/Campaigns/Changed Type.{CampaignSeq,0}","Section1/Campaigns/Changed Type.{Type,1}","Section1/Campaigns/Changed Type.{Name,2}","Section1/Campaigns/Changed Type.{Factor,3}"],"RelationshipInfo":[]}

	annotation PBI_ResultType = Table

