table Industries

	column Industry
		dataType: string
		summarizeBy: none
		sourceColumn: Industry

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

	column IndustrySeq
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: IndustrySeq

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation PBI_ChangedProperties = ["IsHidden"]

	partition Industries-ad0b018f-e5af-41ce-a3f4-c734e885246e = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://microsoft-my.sharepoint.com/personal/misewell_microsoft_com/Documents/Documents/GitHub/ContosoBI/Contoso%20-%20Sales%20-%20Current%20Release/Contoso%20-%20Dynamics%20365%20Sales%20Source%20Data.xlsx"), null, true),
				    IndustryTbl_Table = Source{[Item="IndustryTbl",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(IndustryTbl_Table,{{"IndustrySeq", Int64.Type}, {"Industry", type text}, {"Factor", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Factor"})
				in
				    #"Removed Columns"

	annotation PBI_QueryRelationships = {"columnCount":2,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Section1/Industries/Changed Type.{IndustrySeq,0}","Section1/Industries/Changed Type.{Industry,1}"],"ColumnCount":2,"KeyColumnNames":[],"ColumnIdentities":["Section1/Industries/Changed Type.{IndustrySeq,0}","Section1/Industries/Changed Type.{Industry,1}"],"RelationshipInfo":[]}

	annotation PBI_ResultType = Table

	annotation PBI_ChangedProperties = ["IsHidden"]

