table 'Opportunity Forecast Adjustment'
	isHidden

	measure 'Forecast Adjustment Value' = SELECTEDVALUE('Opportunity Forecast Adjustment'[Forecast Adjustment], 0)
		isHidden

	measure 'Fcst adj slicer alt text' = CONCATENATE("Use the slicer to adjust the forecast, current value is ", 'Opportunity Forecast Adjustment'[Forecast Adjustment Value])

		annotation Format = <Format Format="Text" />

	column 'Forecast Adjustment'
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

	column Blank = 1
		isHidden
		formatString: 0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation PBI_ChangedProperties = ["IsHidden"]

	partition 'Opportunity Forecast Adjustment-9797fe06-d1a1-4be5-b759-4144a437eb58' = calculated
		mode: import
		source = GENERATESERIES(-80, 20, 10)

