table Owners

	measure 'Rev Goal' = ```
			
			VAR RevenueInPipeline =
			    CALCULATE (
			        SUMX ( Opportunities, Opportunities[Value] ),
			        FILTER (
			            Opportunities,
			            Opportunities[Status] = "Open"
			            && VALUE(LEFT(Opportunities[Sales Stage],1)) >=2
			        )
			    )
			VAR BaseGoal =  
			MROUND(([Revenue Won]+ (RevenueInPipeline*.60)),1000000)    
			RETURN
			IF(BaseGoal > 0, BaseGoal, MROUND(([Revenue Won]+ (RevenueInPipeline*.60)),100000))
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############

		annotation PBI_ChangedProperties = ["FormatString"]

		annotation Format = <Format Format="CurrencyGeneral" ThousandSeparator="True"><Currency LCID="0" DisplayName="Currency General" Symbol="$" PositivePattern="0" NegativePattern="0" /></Format>

	column Owner
		dataType: string
		summarizeBy: none
		sourceColumn: Owner

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

	column Manager
		dataType: string
		summarizeBy: none
		sourceColumn: Manager

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

	column SystemUserSeq
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: SystemUserSeq

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="NumberWhole" Accuracy="0" />

		annotation PBI_ChangedProperties = ["IsHidden"]

	column systemuserid
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: systemuserid

		annotation SummarizationSetBy = Automatic

		annotation Format = <Format Format="Text" />

		annotation PBI_ChangedProperties = ["IsHidden"]

	partition Owners-6403f03d-aca3-423f-9155-a1097b964223 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://microsoft-my.sharepoint.com/personal/misewell_microsoft_com/Documents/Documents/GitHub/ContosoBI/Contoso%20-%20Sales%20-%20Current%20Release/Contoso%20-%20Dynamics%20365%20Sales%20Source%20Data.xlsx"), null, true),
				    OwnerTbl_Table = Source{[Item="OwnerTbl",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(OwnerTbl_Table,{{"Owner", type text}, {"Factor", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Factor", "ManagerSeq", "Manager Factor"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"SystemUserSeq", Int64.Type}})
				in
				    #"Changed Type1"

	annotation PBI_QueryRelationships = {"columnCount":3,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Section1/Owners/Changed Type1.{SystemUserSeq,0}","Section1/Owners/Changed Type.{Owner,1}","Section1/Owners/OwnerTbl_Table.{Manager,2}"],"ColumnCount":3,"KeyColumnNames":[],"ColumnIdentities":["Section1/Owners/Changed Type1.{SystemUserSeq,0}","Section1/Owners/Changed Type.{Owner,1}","Section1/Owners/OwnerTbl_Table.{Manager,2}"],"RelationshipInfo":[]}

	annotation PBI_ResultType = Table

